### ISSUE TITLE
Cannot assign to 'current' because it is a read-only property

### ISSUE THREAD

**Issue by FieldMarshallVague** [SKLINET/strapi-plugin-tinymce#1]
Hi there,

I'm trying to add the package to my strapi install, but get the above error when I build (immediately following the install).  

I'm using Strapi 4.3.8 with strapi-plugin-package 1.0.0.
Node is 16.17.0 and npm is 8.15.0.

I've cleared .cache folder and rebuilt, but still problem appears.

It seems to be due to a ref being assigned a null.  This can maybe be avoided by using 'string | null' or similar as the type for that ref.

**Comment by FieldMarshallVague** [comment]
The error output is a mess of escaped characters, but I'll paste it below for reference:

```
[
  {
    file: './src/plugins/test-plugin/admin/src/components/Initializer/index.tsx \x1B[32m\x1B[1m16:7-14\x1B[22m\x1B[39m',
    message: "\x1B[90mTS2540: \x1B[39mCannot assign to 'current' because it is a read-only property.\r\n" +
      '  \x1B[0m \x1B[90m 14 |\x1B[39m \x1B[36mconst\x1B[39m \x1B[33mInitializer\x1B[39m\x1B[33m:\x1B[39m \x1B[33mReact\x1B[39m\x1B[33m.\x1B[39m\x1B[33mFC\x1B[39m\x1B[33m<\x1B[39m\x1B[33mInitializerProps\x1B[39m\x1B[33m>\x1B[39m \x1B[33m=\x1B[39m ({ setPlugin }) \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 15 |\x1B[39m   \x1B[36mconst\x1B[39m ref \x1B[33m=\x1B[39m useRef\x1B[33m<\x1B[39m(id\x1B[33m:\x1B[39m string) \x1B[33m=>\x1B[39m \x1B[36mvoid\x1B[39m \x1B[33m|\x1B[39m \x1B[36mnull\x1B[39m\x1B[33m>\x1B[39m(\x1B[36mnull\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 16 |\x1B[39m   ref\x1B[33m.\x1B[39mcurrent \x1B[33m=\x1B[39m setPlugin\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 17 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 18 |\x1B[39m   useEffect(() \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 19 |\x1B[39m     ref\x1B[33m.\x1B[39mcurrent(pluginId)\x1B[33m;\x1B[39m\x1B[0m',
    details: undefined,
    stack: "Error: \x1B[90mTS2540: \x1B[39mCannot assign to 'current' because it is a read-only property.\r\n" +
      '  \x1B[0m \x1B[90m 14 |\x1B[39m \x1B[36mconst\x1B[39m \x1B[33mInitializer\x1B[39m\x1B[33m:\x1B[39m \x1B[33mReact\x1B[39m\x1B[33m.\x1B[39m\x1B[33mFC\x1B[39m\x1B[33m<\x1B[39m\x1B[33mInitializerProps\x1B[39m\x1B[33m>\x1B[39m \x1B[33m=\x1B[39m ({ setPlugin }) \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 15 |\x1B[39m   \x1B[36mconst\x1B[39m ref \x1B[33m=\x1B[39m useRef\x1B[33m<\x1B[39m(id\x1B[33m:\x1B[39m string) \x1B[33m=>\x1B[39m \x1B[36mvoid\x1B[39m \x1B[33m|\x1B[39m \x1B[36mnull\x1B[39m\x1B[33m>\x1B[39m(\x1B[36mnull\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 16 |\x1B[39m   ref\x1B[33m.\x1B[39mcurrent \x1B[33m=\x1B[39m setPlugin\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 17 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 18 |\x1B[39m   useEffect(() \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 19 |\x1B[39m     ref\x1B[33m.\x1B[39mcurrent(pluginId)\x1B[33m;\x1B[39m\x1B[0m\n' +
      '    at C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:42:27\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:41:16\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:5:58)'
  },
  {
    file: './src/plugins/test-plugin/admin/src/components/Initializer/index.tsx \x1B[32m\x1B[1m19:5-16\x1B[22m\x1B[39m',
    message: "\x1B[90mTS2721: \x1B[39mCannot invoke an object which is possibly 'null'.\r\n" +
      '  \x1B[0m \x1B[90m 17 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 18 |\x1B[39m   useEffect(() \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 19 |\x1B[39m     ref\x1B[33m.\x1B[39mcurrent(pluginId)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m     \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 20 |\x1B[39m   }\x1B[33m,\x1B[39m [])\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 21 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 22 |\x1B[39m   \x1B[36mreturn\x1B[39m \x1B[36mnull\x1B[39m\x1B[33m;\x1B[39m\x1B[0m',
    details: undefined,
    stack: "Error: \x1B[90mTS2721: \x1B[39mCannot invoke an object which is possibly 'null'.\r\n" +
      '  \x1B[0m \x1B[90m 17 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 18 |\x1B[39m   useEffect(() \x1B[33m=>\x1B[39m {\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 19 |\x1B[39m     ref\x1B[33m.\x1B[39mcurrent(pluginId)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m     \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 20 |\x1B[39m   }\x1B[33m,\x1B[39m [])\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 21 |\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 22 |\x1B[39m   \x1B[36mreturn\x1B[39m \x1B[36mnull\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
      '    at C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:42:27\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:41:16\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (C:\\projects\\perfectit\\repos\\PerfectItWebStrapi\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:5:58)'
  }
]
```

**Comment by FieldMarshallVague** [comment]
Sorry this doesn't seem to be related to your plugin, it still persists when I remove it.

**Comment by Sklico** [comment]
Hi @FieldMarshallVague, thanks for info, if I understand it properly, can we close this issue ?

Thanks

**Comment by FieldMarshallVague** [comment]
Yes, sorry for confusion.  It was a coincidence (I'm still not sure why, but that's not your problem! :)

**Comment by FieldMarshallVague** [comment]
BTW, my issue was due to something in Strapi core, which appeared due to adding a package (I'd done a manual fix to a node dependency, which was overwritten by the NPM install process).  It's not related to this package or repo, I just put it here for completeness.

https://github.com/strapi/strapi/issues/12960

That thread includes the manual fix, but beware, it will get overwritten until they patch it.
